import type {Metadata} from "next";
import {Inter} from "next/font/google";
import './globals.css'
import 'tailwindcss/tailwind.css'
import Header from "@/components/layout/Header";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className} flex flex-col items-center`}>
    <Header/>
    <main>{children}</main>
    </body>
    </html>
  );
}
